/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author edanrylmaz
 */
public class Kitap_Ara extends javax.swing.JFrame {

    /**
     * Creates new form Kitap_Ara
     */
    public Kitap_Ara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        YazarAramaTF = new javax.swing.JTextField();
        YazarAraButon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        KitapAramaTF = new javax.swing.JTextField();
        KitapAraButon = new javax.swing.JButton();
        AnaMenuButon = new javax.swing.JButton();
        CikisButon = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kitapAraTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        yazarAraTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 6, 6));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("ARAMA EKRANINA HOŞGELDİNİZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(152, 141, 70));

        YazarAramaTF.setBackground(new java.awt.Color(240, 207, 207));
        YazarAramaTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        YazarAramaTF.setText("Anahtar Kelimeyi Giriniz...");
        YazarAramaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                YazarAramaTFFocusGained(evt);
            }
        });

        YazarAraButon.setBackground(new java.awt.Color(152, 141, 70));
        YazarAraButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        YazarAraButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/magnifier-icon.png"))); // NOI18N
        YazarAraButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YazarAraButonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("   YAZAR ADINA GÖRE ARAMA");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("   KİTAP ADINA GÖRE ARAMA");

        KitapAramaTF.setBackground(new java.awt.Color(240, 207, 207));
        KitapAramaTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KitapAramaTF.setForeground(new java.awt.Color(1, 1, 1));
        KitapAramaTF.setText("Anahtar Kelimeyi Giriniz...");
        KitapAramaTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KitapAramaTFFocusGained(evt);
            }
        });

        KitapAraButon.setBackground(new java.awt.Color(152, 141, 70));
        KitapAraButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        KitapAraButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/magnifier-icon.png"))); // NOI18N
        KitapAraButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KitapAraButonActionPerformed(evt);
            }
        });

        AnaMenuButon.setBackground(new java.awt.Color(152, 141, 70));
        AnaMenuButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AnaMenuButon.setForeground(new java.awt.Color(1, 1, 1));
        AnaMenuButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/home-icon(1).png"))); // NOI18N
        AnaMenuButon.setToolTipText("ANA MENÜ");
        AnaMenuButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaMenuButonActionPerformed(evt);
            }
        });

        CikisButon.setBackground(new java.awt.Color(152, 141, 70));
        CikisButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CikisButon.setForeground(new java.awt.Color(1, 1, 1));
        CikisButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/users-exit-icon(1).png"))); // NOI18N
        CikisButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CikisButonActionPerformed(evt);
            }
        });

        kitapAraTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kitapAraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KİTAP ADI", "YAZAR ADI", "ADET"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(kitapAraTable);

        yazarAraTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        yazarAraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KİTAP ADI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(yazarAraTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YazarAramaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YazarAraButon))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(KitapAramaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(KitapAraButon)))
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(AnaMenuButon)
                        .addGap(71, 71, 71)
                        .addComponent(CikisButon)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YazarAramaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KitapAramaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KitapAraButon)
                            .addComponent(YazarAraButon))
                        .addGap(83, 83, 83)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(208, 208, 208)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CikisButon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AnaMenuButon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CikisButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CikisButonActionPerformed
        login don =new login();
        don.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CikisButonActionPerformed

    private void AnaMenuButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaMenuButonActionPerformed
        Ana_Menu don = new Ana_Menu();
        don.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AnaMenuButonActionPerformed

    private void KitapAraButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KitapAraButonActionPerformed
        String query ="select kitap_adi,yazar,adet from kitaplar where kitap_adi LIKE '%"+KitapAramaTF.getText()+"%'";
        DefaultTableModel kitapAraModel = (DefaultTableModel) kitapAraTable.getModel();
        Object satir [] = new Object [3];
        kitapAraModel.setRowCount(0);
        
        try {
            Database db = new Database();
            db.rs=db.st.executeQuery(query);
            while(db.rs.next()){
                satir[0]=db.rs.getString(1);
                satir[1]=db.rs.getString(2);
                satir[2]=db.rs.getInt(3);
                kitapAraModel.addRow(satir);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Kitap_Ara.class.getName()).log(Level.SEVERE, null, ex);
        }
       

        
       
    }//GEN-LAST:event_KitapAraButonActionPerformed

    private void KitapAramaTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KitapAramaTFFocusGained
        KitapAramaTF.setText("");
    }//GEN-LAST:event_KitapAramaTFFocusGained

    private void YazarAramaTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_YazarAramaTFFocusGained
        YazarAramaTF.setText("");
    }//GEN-LAST:event_YazarAramaTFFocusGained

    private void YazarAraButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YazarAraButonActionPerformed
        String query="select kitap_adi from kitaplar where yazar LIKE '%"+YazarAramaTF.getText()+"%'";
        DefaultTableModel yazarAraModel = (DefaultTableModel) yazarAraTable.getModel();
        Object satir [] = new Object[1];
        yazarAraModel.setRowCount(0);
        try {
            Database db =new Database();
            db.rs=db.st.executeQuery(query);
            while(db.rs.next()){
            satir[0]=db.rs.getString(1);
            yazarAraModel.addRow(satir);
        }
        } 
        catch (SQLException ex) {
            Logger.getLogger(Kitap_Ara.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_YazarAraButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitap_Ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitap_Ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitap_Ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitap_Ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitap_Ara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnaMenuButon;
    private javax.swing.JButton CikisButon;
    private javax.swing.JButton KitapAraButon;
    private javax.swing.JTextField KitapAramaTF;
    private javax.swing.JButton YazarAraButon;
    private javax.swing.JTextField YazarAramaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable kitapAraTable;
    private javax.swing.JTable yazarAraTable;
    // End of variables declaration//GEN-END:variables
}
