/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author edanrylmaz
 */
public class Kitap_birak extends javax.swing.JFrame {

    static String kullaniciAdi =new String();
    public Kitap_birak(String x) {
        kullaniciAdi =x;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iadeEtButon = new javax.swing.JButton();
        AnaMenuButon = new javax.swing.JButton();
        CikisButon = new javax.swing.JButton();
        yenileButon = new javax.swing.JButton();
        iadeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("İADE İŞLEMLERİ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(152, 141, 70));

        iadeEtButon.setBackground(new java.awt.Color(240, 207, 207));
        iadeEtButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        iadeEtButon.setText("İADE ET");
        iadeEtButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iadeEtButonActionPerformed(evt);
            }
        });

        AnaMenuButon.setBackground(new java.awt.Color(152, 141, 70));
        AnaMenuButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AnaMenuButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/home-icon(1).png"))); // NOI18N
        AnaMenuButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaMenuButonActionPerformed(evt);
            }
        });

        CikisButon.setBackground(new java.awt.Color(152, 141, 70));
        CikisButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CikisButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/users-exit-icon(1).png"))); // NOI18N
        CikisButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CikisButonActionPerformed(evt);
            }
        });

        yenileButon.setBackground(new java.awt.Color(240, 207, 207));
        yenileButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        yenileButon.setText("YENİLE");
        yenileButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenileButonActionPerformed(evt);
            }
        });

        iadeComboBox.setBackground(new java.awt.Color(254, 254, 254));
        iadeComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        iadeComboBox.setForeground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(AnaMenuButon)
                .addGap(51, 51, 51)
                .addComponent(CikisButon)
                .addGap(45, 45, 45))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(iadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(yenileButon, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(iadeEtButon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenileButon, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(iadeEtButon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CikisButon)
                    .addComponent(AnaMenuButon))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CikisButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CikisButonActionPerformed
        login don = new login();
        don.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CikisButonActionPerformed

    private void AnaMenuButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaMenuButonActionPerformed
        Ana_Menu don = new Ana_Menu();
        don.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AnaMenuButonActionPerformed

    private void yenileButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenileButonActionPerformed
        iadeComboBox.removeAllItems();
        String query ="select kitap_1,kitap_2,kitap_3 from kullanici where kullanici_adi ='"+kullaniciAdi+"'";
        try {
            Database db =new Database();
            db.rs=db.st.executeQuery(query);
            while(db.rs.next()){
                iadeComboBox.addItem(db.rs.getString(1));
                iadeComboBox.addItem(db.rs.getString(2));
                iadeComboBox.addItem(db.rs.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Kitap_birak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yenileButonActionPerformed

    private void iadeEtButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iadeEtButonActionPerformed
       String queryKitapAdet="UPDATE kitaplar SET adet= adet+1 where kitap_adi='"+iadeComboBox.getSelectedItem()+"'";
       String queryKullaniciUygunluk="UPDATE kullanici SET uygunluk = uygunluk+1 where kullanici_adi='"+kullaniciAdi+"'";
       if(iadeComboBox.getSelectedItem().equals("")){
           JOptionPane.showMessageDialog(null, "LÜTFEN BİR KİTSP SEÇİNİZ");
           return;
       }
       String queryUpdate1= "UPDATE kullanici SET kitap_1 =NULL ";
       String queryUpdate2= "UPDATE kullanici SET kitap_2 =NULL ";
       String queryUpdate3= "UPDATE kullanici SET kitap_3 =NULL ";
       String queryUpdate4= "UPDATE kullanici SET kitap_1_donus =NULL ";
       String queryUpdate5= "UPDATE kullanici SET kitap_2_donus =NULL ";
       String queryUpdate6= "UPDATE kullanici SET kitap_3_donus =NULL ";
        try {
            Database db = new Database();
            if(iadeComboBox.getSelectedIndex()==0){
             db.st.executeUpdate(queryUpdate1);
             db.st.executeUpdate(queryUpdate4);
             db.st.executeUpdate(queryKitapAdet);
             db.st.executeUpdate(queryKullaniciUygunluk);
             iadeComboBox.removeAllItems();
             return;
            }else if(iadeComboBox.getSelectedIndex()==1){
                db.st.executeUpdate(queryUpdate2);
                db.st.executeUpdate(queryUpdate5);
                db.st.executeUpdate(queryKitapAdet);
                db.st.executeUpdate(queryKullaniciUygunluk);
                iadeComboBox.removeAllItems();
                return;
            }else if(iadeComboBox.getSelectedIndex()==2){
                db.st.executeUpdate(queryUpdate3);
                db.st.executeUpdate(queryUpdate6);
                db.st.executeUpdate(queryKitapAdet);
                db.st.executeUpdate(queryKullaniciUygunluk);
                iadeComboBox.removeAllItems();
                return;
            }
            
            JOptionPane.showMessageDialog(null,"İADE İŞLEMİNİZ BAŞARIYLA GERÇEKLEŞTİ.\nYENİLE BUTONUNA BASARAK KONTROL EDEBİLİRSİNİZ.");
            
        } catch (SQLException ex) {
            Logger.getLogger(Kitap_birak.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_iadeEtButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitap_birak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitap_birak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitap_birak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitap_birak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitap_birak(kullaniciAdi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnaMenuButon;
    private javax.swing.JButton CikisButon;
    private javax.swing.JComboBox<String> iadeComboBox;
    private javax.swing.JButton iadeEtButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton yenileButon;
    // End of variables declaration//GEN-END:variables
}
