/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje;

import com.mysql.fabric.xmlrpc.base.Data;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author edanrylmaz
 */
public class Odunc_Al extends javax.swing.JFrame {

    static String kullaniciAdi=new String();
    public Odunc_Al(String x) {
        kullaniciAdi =x;
        initComponents();
    }

    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kitapAlButon = new javax.swing.JButton();
        CikisButton = new javax.swing.JButton();
        AnaMenuButon = new javax.swing.JButton();
        kitaplarComboBox = new javax.swing.JComboBox<>();
        yenileButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(152, 141, 70));

        kitapAlButon.setBackground(new java.awt.Color(240, 207, 207));
        kitapAlButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        kitapAlButon.setText("ONAYLA");
        kitapAlButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapAlButonActionPerformed(evt);
            }
        });

        CikisButton.setBackground(new java.awt.Color(152, 141, 70));
        CikisButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CikisButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/users-exit-icon(1).png"))); // NOI18N
        CikisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CikisButtonActionPerformed(evt);
            }
        });

        AnaMenuButon.setBackground(new java.awt.Color(152, 141, 70));
        AnaMenuButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AnaMenuButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proje/home-icon(1).png"))); // NOI18N
        AnaMenuButon.setPreferredSize(new java.awt.Dimension(64, 54));
        AnaMenuButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaMenuButonActionPerformed(evt);
            }
        });

        kitaplarComboBox.setBackground(new java.awt.Color(254, 254, 254));
        kitaplarComboBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        yenileButton.setBackground(new java.awt.Color(240, 207, 207));
        yenileButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        yenileButton.setText("YENİLE");
        yenileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AnaMenuButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(CikisButton)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(kitaplarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(yenileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(kitapAlButon, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kitaplarComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(kitapAlButon, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AnaMenuButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CikisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 102, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(32, 18, 18));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 252, 252));
        jLabel1.setText("KİTAP ÖDÜNÇ ALMA EKRANINA  HOŞGELDİNİZ ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CikisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CikisButtonActionPerformed
       login don =new login();
       don.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_CikisButtonActionPerformed

    private void AnaMenuButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaMenuButonActionPerformed
        Ana_Menu don = new Ana_Menu();
        don.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AnaMenuButonActionPerformed

    private void kitapAlButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapAlButonActionPerformed
        String queryKitapAdet="Select adet from kitaplar where kitap_adi='"+kitaplarComboBox.getSelectedItem()+"'";
        String queryKullaniciUygunluk="Select uygunluk from kullanici where kullanici_adi='"+kullaniciAdi+"'";
        String queryUpdate= new String();
        String queryUpdate1="UPDATE kullanici SET kitap_1='"+kitaplarComboBox.getSelectedItem()+"',kitap_1_donus=DATE_ADD(CURDATE(),INTERVAL 1 MONTH), uygunluk=2 where kullanici_adi='"+kullaniciAdi+"'";
        String queryUpdate2="UPDATE kullanici SET kitap_2='"+kitaplarComboBox.getSelectedItem()+"',kitap_2_donus=DATE_ADD(CURDATE(),INTERVAL 1 MONTH), uygunluk=1 where kullanici_adi='"+kullaniciAdi+"'";
        String queryUpdate3="UPDATE kullanici SET kitap_3='"+kitaplarComboBox.getSelectedItem()+"',kitap_3_donus=DATE_ADD(CURDATE(),INTERVAL 1 MONTH), uygunluk=0 where kullanici_adi='"+kullaniciAdi+"'";
        String queryUpdateKitap="UPDATE kitaplar SET adet=adet-1 where kitap_adi='"+kitaplarComboBox.getSelectedItem()+"'";
        
        try {
            Database db=new Database();
            db.rs=db.st.executeQuery(queryKitapAdet);
            db.rs.next();
            if(db.rs.getInt(1)<=0){
                kitaplarComboBox.removeAllItems();
                return;
            }
            db.rs.close();
            db.rs=db.st.executeQuery(queryKullaniciUygunluk);
            db.rs.next();
            if(db.rs.getInt(1)==3){
                queryUpdate=queryUpdate1;
            }else if(db.rs.getInt(1)==2){
                queryUpdate=queryUpdate2;
            }else if(db.rs.getInt(1)==1){
                queryUpdate=queryUpdate3;
            }else {
                kitaplarComboBox.removeAllItems();
                return;
            }
            db.rs.close();
            db.st.executeUpdate(queryUpdate);
            db.st.executeUpdate(queryUpdateKitap);
            JOptionPane.showMessageDialog(null, "ÖDÜNÇ ALMA İŞLEMİNİZ BAŞARIYLA GERÇEKLEŞTİRİLDİ! \n KITAPLARIM SAYFASINDAN ODÜNÇ ALDIĞINIZ KİTAPLARI GÖREBİLİRSİNİZ.ALDIĞINIZ KİTAPLARI GÖREBİLİRSİNİZ!");
            
        } catch (SQLException ex) {
            Logger.getLogger(Odunc_Al.class.getName()).log(Level.SEVERE, null, ex);
        }
        kitaplarComboBox.removeAllItems();
        
    }//GEN-LAST:event_kitapAlButonActionPerformed

    private void yenileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenileButtonActionPerformed
        
        String query="Select kitap_adi from kitaplar where adet>0";
        kitaplarComboBox.removeAllItems();
        
        try {
            Database db=new Database();
            db.rs=db.st.executeQuery(query);
            while(db.rs.next()){
                kitaplarComboBox.addItem(db.rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Odunc_Al.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_yenileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odunc_Al.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odunc_Al.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odunc_Al.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odunc_Al.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odunc_Al(kullaniciAdi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnaMenuButon;
    private javax.swing.JButton CikisButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kitapAlButon;
    private javax.swing.JComboBox<String> kitaplarComboBox;
    private javax.swing.JButton yenileButton;
    // End of variables declaration//GEN-END:variables
}
